### ISSUE TITLE
Asynchronous background fetching causes confusing behavior if items are requested before they are done being fetched

### ISSUE THREAD

**Issue by ymost** [Azure/pykusto#111]
Example code:

    client = PyKustoClient(CLUSTER)
    client.get_databases_names()

This might return an empty list because fetching the list of databases in the background did not finish yet. This is confusing for the user, who might think there are no databases, or that there is a bug in getting the list.

Possible solutions:

1. Print a log message to explain why the returned list is empty.
1. Make the various "get_" methods blocking.

**Comment by DaniellePoleg** [comment]
We encountered this also in table.get_columns()
