### ISSUE TITLE
add retry mechanism for queries that fail due to throttling

### ISSUE THREAD

**Issue by DaniellePoleg** [Azure/pykusto#132]
Due to limited resources queries can fail, and the error message implies the query was throttled since the threshold was reached ((KustoServiceError(...), [{'error': {'code': 'Too many requests', 'message': 'Request is denied due to throttling.',)
We can add a retry mechanism with exponential backoff that will catch this exception and hopefully will decrease the failures.

**Comment by ymost** [comment]
This looks like a good package to use:
https://pypi.org/project/redo
