### ISSUE TITLE
iff function - type comparison does not compare correctly int and f.array_length({array})

### ISSUE THREAD

**Issue by micky-amir** [Azure/pykusto#47]
f.iff function checks if both return options return the same type.
consider this code:
```
Query.extend(some_data_count=
                                  f.iff(some_condition,
                                        f.array_length(col.some_date),
                                        0)))
```
throws:
`pykusto/functions.py", line 271, in iff
    raise TypeError("The second and third arguments must be of the same type")
TypeError: The second and third arguments must be of the same type`

**Comment by ymost** [comment]
This was solved in #45, and will be included in version 0.0.10, which was not released yet.
@shaike87 can we release version 0.0.10 so we can close this bug?
